#!/bin/sh

$HOME/.config/dwm/dwmbar/dwm_bar.sh &   # Maybe it's time to change dwmbar to dwmblocks

xrandr --dpi 96
setbg &
xbacklight -set 50 &
xrandr --output HDMI1 --auto --scale 1.0x1.0 --output eDP1 --right-of HDMI1 &
xrandr --output HDMI1 --primary --mode 1920x1080 --rate 60 &
remaps &
pipewire &

autostart="mpd xcompmgr dunst unclutter"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
